### ISSUE TITLE
Crash in BlurLayout

### ISSUE THREAD

**Issue by dinghaoz** [Giphy/giphy-android-sdk#121] opened 2021-02-22 09:06 UTC
Brand: samsung
Model: Galaxy J6
Orientation: Portrait
RAM free: 239.84 MB
Disk free: 8.75 GB

Version: 9
Orientation: Portrait
Rooted: No

Fatal Exception: java.lang.IllegalArgumentException: height must be > 0
       at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:447)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:811)
       at io.alterac.blurkit.BlurLayout.blur(BlurLayout.java:276)
       at io.alterac.blurkit.BlurLayout.invalidate(BlurLayout.java:164)
       at io.alterac.blurkit.BlurLayout.onSizeChanged(BlurLayout.java:158)
       at android.view.View.sizeChange(View.java:22601)
       at android.view.View.setFrame(View.java:22543)
       at android.view.View.layout(View.java:22403)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1843)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1087)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3414)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2883)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1931)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8578)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7081)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by ALexanderLonsky** [comment] 2021-02-22 15:12
Duplicate of #80

**Comment by ALexanderLonsky** [comment] 2021-06-21 06:31
BlurKit was removed from the SDK as of [v2.1.1](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.1.1)

**Closed by ALexanderLonsky** 2021-06-21 06:31 UTC
