### ISSUE TITLE
Text color appears black in Dark Theme.

### ISSUE THREAD

**Issue by sonusinha-ptw** [Giphy/giphy-android-sdk#199] opened 2023-05-10 13:10 UTC
## 🐛 Bug Report

Searching for something without the Internet error text showing up (Oh No! something went wrong) in Black Color.
can we have control over it, how can I change the color of this text.?
![Screenshot_1683723635](https://github.com/Giphy/giphy-android-sdk/assets/53182795/0a62a3b7-813e-45e2-a834-c55128862f34)

**Comment by ALexanderLonsky** [comment] 2023-05-10 16:21
Hey @sonusinha-ptw,
Thanks for flagging this issue!
We're working on a new release that will offer a wider range of colors for customization.
There's version available now, so you can give it a try:

`implementation "com.giphy.sdk:ui:2.3.5-rc2"`

It's a staging version and requires to add:

```
allprojects {
    repositories {
        maven("https://oss.sonatype.org/content/repositories/staging")
        mavenCentral()
    }
}
```

Additionally, it resolves the issue with the error message.

To customize colors you need to use `GPHTheme.Custom`

```
var settings = GPHSettings(theme = GPHTheme.Custom)
```

Then modify the required colors in this way:
```
GPHCustomTheme.apply {
            val currentNightMode = this@DemoActivity?.let {
                this@DemoActivity.resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
            }
            val lightMode = (listOf(Configuration.UI_MODE_NIGHT_NO, Configuration.UI_MODE_NIGHT_UNDEFINED).contains(currentNightMode))

            if (lightMode) {
                defaultTextColor= 0xFF5C5C5C.toInt()
            } else {
                defaultTextColor= 0xFFFFFFFF.toInt()
            }
        }
```

If you need any clarification, please let me know.

**Comment by ALexanderLonsky** [comment] 2023-05-12 14:37
P.S.
However, if you want to use the custom theme, you must redefine all colors for dark mode, as the default custom theme is a duplicate of the light one (unfortunately, there is currently no support for this scenario):

```
GPHCustomTheme.apply {
            val currentNightMode = this@DemoActivity?.let {
                this@DemoActivity.resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
            }
            val lightMode = (listOf(Configuration.UI_MODE_NIGHT_NO, Configuration.UI_MODE_NIGHT_UNDEFINED).contains(currentNightMode))
            if (lightMode) {
                searchButtonIcon = ContextCompat.getDrawable(this@DemoActivity, com.giphy.sdk.ui.R.drawable.gph_ic_search_black)
            } else {
                searchButtonIcon = ContextCompat.getDrawable(this@DemoActivity, com.giphy.sdk.ui.R.drawable.gph_ic_search_white)

                handleBarColor = 0xFF888888.toInt()

                emojiDrawerGradientTopColor = 0xFF212121.toInt()
                emojiDrawerGradientBottomColor = 0xFF1B1B1B.toInt()
                emojiDrawerSeparatorColor = 0xFF424242.toInt()

                searchBarBackgroundColor = 0xFF4E4E4E.toInt()
                searchTextColor = 0xFFFFFFFF.toInt()
                searchBackButtonColor = 0xFFFFFFFF.toInt()
                searchPlaceholderTextColor = ColorUtils.setAlphaComponent(searchTextColor, 0xCC)

                suggestionCellBackgroundColor = 0xFF212121.toInt()
                suggestionCellTextColor = 0xFFFFFFFF.toInt()

                tabBarSwitchDefaultColor = 0xC09A9A9A.toInt()
                tabBarSwitchSelectedColor = 0xFF00FF99.toInt()

                confirmationSelectButtonColor = 0xFF00FF99.toInt()
                confirmationSelectButtonTextColor = 0xFF121212.toInt()
                confirmationBackButtonColor = 0xFFD8D8D8.toInt()
                confirmationViewOnGiphyColor = 0xFFA6A6A6.toInt()

                backgroundColor = 0xFF121212.toInt()
                dialogOverlayBackgroundColor = 0x994E4E4E.toInt()
                defaultTextColor = 0xFFFFFFFF.toInt()
                usernameColor = 0xFFD8D8D8.toInt()
            }
        }
```

**Comment by ALexanderLonsky** [comment] 2023-05-12 15:02
Update:

https://github.com/Giphy/giphy-android-sdk/issues/200#issuecomment-1545883072

**Comment by ALexanderLonsky** [comment] 2023-05-25 07:49
The [new version](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.3.5) has been released.

**Closed by ALexanderLonsky** 2023-05-25 07:49 UTC
Labels: bug
